[build]
  publish = "public"
  command = "npm install"
  functions = "netlify/functions"

[functions]
  [functions.grok-prediction]
    timeout = 30

[build.environment]
  # API keys are set in Netlify dashboard, not in build config

# Serve JSON files directly
[[redirects]]
  from = "/data/*.json"
  to = "/data/:splat"
  status = 200

# Redirect everything else to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" # Trigger redeploy: Fri Aug  8 18:03:13 +01 2025

# Add headers for JSON files
[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, max-age=300"
    Content-Type = "application/json"
