name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Copy data files to public
      run: |
        mkdir -p public/data
        cp data/processed_matches.json public/data/ 2>/dev/null || echo "processed_matches.json not found"
        cp data/analysis.json public/data/ 2>/dev/null || echo "analysis.json not found"
        cp data/comparison.json public/data/ 2>/dev/null || echo "comparison.json not found"
        echo "Data files copied to public/data directory"
        
    - name: Build static files
      run: |
        echo "Static files built successfully"
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './public'
        
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 